CBL-3421 Handle empty or invalid string in proxy host
couchbase/couchbase-lite-net pull request #1404
Opened 2022-07-18 18:28 UTC by Sandychuang8

2022-07-18 19:23 UTC, borrrden requested changes
Just to be miserably safe, let's use TryParse on the port number too.

2022-07-18 22:21 UTC, Sandychuang8 commented on src/Couchbase.Lite.Shared/Support/Android/XamarinAndroidProxy.cs
> +            return Task.FromResult(new WebProxy(validUri.Host, validPort));
At the end I used try catch to catch any exception throw when failed creating WebProxy... I guess this maybe the safest way... 65536 as port value will receive [UriFormatException](https://docs.microsoft.com/en-us/dotnet/api/system.uriformatexception?view=net-6.0) I have added some test cases for verification purpose...

2022-07-19 16:35 UTC, borrrden approved these changes

2022-07-19 16:36 UTC, borrrden commented on src/Couchbase.Lite.Shared/Support/Android/XamarinAndroidProxy.cs
> +            return Task.FromResult(new WebProxy(validUri.Host, validPort));
In the end this is the most failsafe way, probably

2022-07-19 17:39 UTC, merged