CBL-3628 Maui test project to include Android platform
couchbase/couchbase-lite-net pull request #1432
Opened 2022-09-26 03:51 UTC by Sandychuang8

2022-09-30 00:23 UTC, borrrden requested changes
Quite hard to tell what all these changes are for, but a few comments

2022-09-30 00:23 UTC, borrrden commented on src/Couchbase.Lite.Shared/Sync/HTTPLogic.cs
> +            //var commit = ThisAssembly.Git.Commit;
Why?

2022-09-30 00:23 UTC, borrrden commented on src/Couchbase.Lite.Support.Android/Activate.cs
> +        public static void CheckVersion()
This is not the way to handle this, did you use the `InternalsVisibleTo` attribute?

2022-09-30 00:23 UTC, borrrden commented on src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj
> +  </PropertyGroup>
This is repetitive.  Why not just use targetframework?

2022-09-30 01:07 UTC, Sandychuang8 commented on src/Couchbase.Lite.Shared/Sync/HTTPLogic.cs
> +            //var commit = ThisAssembly.Git.Commit;
strange, I thought I have already uncommented these...

2022-10-04 01:08 UTC, borrrden approved these changes

2022-10-04 01:28 UTC, merged